# -*- coding: utf-8 -*-
"""0.2.EDA_inicial_llamadas123.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bU86A_gKldSF98lM2GsixkksoO1XmsYu
"""

# importar librerias para manipulacion de datos
import numpy  as np
import pandas as pd

# importar librerias para visualizacion
import matplotlib.pyplot as plt


# importar librerias internas del sistema
import os
from pathlib import Path

# Ruta de los archivos de datos

current_dir = Path(".").resolve()
project_dir = Path(current_dir).parent

print("Directorio actual   ", current_dir)
print("Directorio principal", project_dir)

# Obtener la ruta donde leer los archivos de datos
filename = "llamadas123_julio_2022.csv"
dir_data = os.path.join(project_dir, "data", "raw")


print(filename, type(filename))
print(dir_data, type(dir_data))

# Leer archivo de datos con extension CSV
data = pd.read_csv(
    os.path.join(dir_data , filename),
    sep = ';',
    encoding = 'latin-1'
)

data.head()

# Tipos de datos

data.dtypes     # Muestra el tipo de variable por cada columna  (esquema de la tabla)

list(data.columns)     # Listas en python son una estructura de datos, utiles para hacer iteraciones

lista_columnas = list(data.columns)

columnas[-1]    # Muestra el contenido de la lista en la posicion (index) indicada

lista_columnas[3:6]    # sliders, perfimenten "navegar" sobre los indices de una lista

print("Cuantas columnas hay?", len(lista_columnas))    # la funcion len() indica el tamano de una lista

# Iterar sobre una lista

# Cuantos valores unicos hay cada columna?
for elem in lista_columnas:
    print(elem, len(data[elem].unique()) )

# Creemos una tabla con el resumen de valores unicos por columna

# crear un dictionario vacio
dict_valores = dict()

# loop para llenar el dictionario
# {
#   "NUMERO_INCIDENTE" : 12015,
#   ...
#   "EDAD" : 100
# }
for elem in lista_columnas:
    dict_valores[elem] = len(data[elem].unique())

# Crea una tabla (pandas.dataframe) desde un dictionario
df_sum = pd.DataFrame.from_dict(dict_valores, orient="index")
df_sum = df_sum.rename({0:"Count"}, axis=1)                    # renombra la columna 0 con Count
df_sum

